### ISSUE TITLE
deepTools2.5.0

### ISSUE THREAD

**Issue by thomasmanke** [IHEC/ihec-assay-standards#2]
The issue with maximal coverage (for large bins) was only fixed in deepTools2.5.0 
https://github.com/fidelram/deepTools/blob/master/CHANGES.txt
it would be safer to refer to this version.

**Comment by sitag** [comment]
I will use 2.5.0 for testing, and update the wrapper when I test it.

**Comment by sitag** [comment]
Fixed here: https://github.com/IHEC/ihec-assay-standards/commit/5681e56386246802207bfef140f5e1dcb595cf14
